services:
  app:
    build: .
    container_name: springboot-chat
    ports:
      - "8080:8080"
    volumes:
      - ./uploads/img_duvidas:/app/uploads/img_duvidas
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
