FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /app/target/chat-0.0.1-SNAPSHOT.jar app.jar

RUN mkdir -p /app/uploads/img_duvidas
VOLUME ["/app/uploads/img_duvidas"]

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
